apiVersion: apps/v1
kind: Deployment
metadata:
   name: worker-app-deployment
   labels:
      app: myapp
      type: worker-app
      
spec:
   template:
      metadata:
         name: worker-app-prod
         labels:
            app: myapp
            type: backend-worker-app
      spec:
         containers:
            - name: vote-app
              image: docker/example-voting-app-worker
                 
   replicas: 1
   selector:
      matchLabels:
         app: myapp
         type: backend-worker-app